[package]
name = "use-frame-rate"
description = "Primitive frame-rate helpers"
publish = true
authors.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
documentation = "https://docs.rs/use-frame-rate"
keywords = ["media", "frame-rate", "fps", "video"]
categories = ["algorithms", "science"]

[lints]
workspace = true