[package]
name = "use-svg"
description = "Practical SVG utility primitives"
publish = true
authors.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
documentation = "https://rustuse.org"
readme = "README.md"
keywords = ["svg", "media", "image", "vector", "graphics"]
categories = ["multimedia::images", "parser-implementations"]

[lints]
workspace = true